#!/usr/bin/env bash

set -e

usage_str="Usage: ${0} [SERVICE] [COMMAND]"

if [ "${1}" = -h ] || \
   [ "${1}" = --help ] || \
   [ "${1}" = help ]; then
  echo $usage_str
  echo
  echo "Executes a command inside a specified docker-compose service"
  exit
else
  if [ "$#" -lt 2 ]; then
    echo "Wrong number of arguments"
    echo $usage_str
    exit 1
  fi
fi

echo "[ dx/exec ] Execution started ..."
echo
docker compose -f docker-compose.dev.yml run --rm "$@"
echo
echo "[ dx/exec ] Execution done!"
