# :verbose: false
:timeout: 25

# Raising concurrency can cause CPU overload. For example, Heroku's basic dynos have very little CPU compared to modern servers.
# :concurrency: 5

# Concurrency can be overridden based on environment as well.
# production:
#   :concurrency: 5
# staging:
#   :concurrency: 5

:queues:
  - default
  - mailers
